[project]
name = "render-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.115.6",
    "psycopg>=3.2.4",
    "sqlalchemy>=2.0.37",
]
